### PR TITLE
Test refactor

### PR DESCRIPTION
**Pull request by vandenoever**
Just some small refactors.

### CODE REVIEW

**Comment by passcod** [comment]
AppVeyor CI failure, for reference:

```
running 5 tests
test new_null ... ok 
test new_poll ... ok 
test new_recommended ... ok 
test watch_dir_recommended ... ok 
test watch_single_file_recommended ... FAILED 
 
failures:
 
---- watch_single_file_recommended stdout ----
	thread 'watch_single_file_recommended' panicked at 'unexpected channel err: Empty', tests\notify.rs:74
note: Run with `RUST_BACKTRACE=1` for a backtrace.
 
 
failures:
    watch_single_file_recommended
 
test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured
 
error: test failed
Command exited with code 101
```

**Comment by passcod** [comment]
(This looks perhaps like a transient failure, so I'm retrying the build.)

**Comment by vandenoever** [comment]
The Receiver got an error that there were no more messages. I updated the PR to break the loop when that happens. (I've no windows, so debugging by updating the PR)

**Comment by passcod** [comment]
Looks good :)

**Pull request merged**
