### PR TITLE
Single file support for inotify

### LINKED ISSUE #16: Support watching single files
Currently the FSEvents backend supports watching single files, the inotify backend doesn't.

Go's fsnotify, Ruby's Listen, Facebook's Watchman and others also do not support watching single files.

__Phase 0__ of this feature is research:
- What is the reason behind lack of support in others?
- What are libraries that do have support?
- What are challenges for an implementation?
- Is this doable in a backend-independent manner?

If that last point can be answered by _yes_, another question is whether this behaviour would be better done in a separate package.

### PR DESCRIPTION
**Pull request by Yuhta**
Fix #16

### CODE REVIEW

**Comment by passcod** [comment]
Great work! Is inotify the only one that needs this, or do the others (polling) also need patching up?

Add yourself to the contributor array in the Cargo.toml :)

@maurizi Not sure if your work on the Windows implementation supports single file watching, is it possible, harder, easy ? Just to let you know we're apparently going to support that now.

**Comment by Yuhta** [comment]
Patched and added `PollWatcher`; I don't have the environment to test `FsEventWatcher` but some one else can easily add it.

**Comment by maurizi** [comment]
@passcod Windows only really has a notion of watching directories, so this will be harder on Windows, since we'll have to add a layer above this that filters out events not for that directory.  Since it looks like `PollWatcher` will need that as well, it might be a good idea to implement it generically.

**Comment by passcod** [comment]
I'm going to merge this to _fix_ #16. FS watchers in general seem to only support watching folders, with exceptions.

So we'll have to figure an internal API, perhaps with traits, so a backend could:
- implement a `FileWatcher` to watch individual files, so we'd have to recurse to watch everything, or
- implement a `DirWatcher` to watch individual folders, so we'd have to recurse to watch subfolders, or
- implement a `RecursiveDirWatcher` to watch everything, or
- any combination of the above

and then Notify itself would take care of wrangling each backend to provide the same public API.

**Pull request merged**
