### PR TITLE
Only register directories for watching

### PR DESCRIPTION
**Pull request by vandenoever**
Directories also report the events for the files in the directories.

### CODE REVIEW

**Comment by passcod** [comment]
Walk me through this. What does your change do? Does it still support calling `add_watch` on a file?

**Comment by vandenoever** [comment]
For normal files there is no need for a watch, so for files instead of calling add_watch, Ok(()) is returned.

**Comment by vandenoever** [comment]
I see now that this patch does not yet support calling add_watch_recursively to register a watch on a single file.

**Comment by passcod** [comment]
This function originally has two scenarios:

- If Path is a file, watch it
- If Path is a dir, watch dir, all subdirs and subfiles

We want:

- If Path is a file, watch it
- If Path is a dir, watch dir and all subdirs only

Your patch does, even the updated version:

- If Path is a file, fail silently
- If Path is a dir, watch dir, all subdirs and subfiles

So, see, what your patch does is silently break a valid use case, and fail to actually address the problem.

**Comment by vandenoever** [comment]
I uploaded a new diff in pull request #76 . I'm on a very bad connection and have a hard time updating the diff on this PR.

**Pull request merged**
