### PR TITLE
Replace Walker by WalkDir

### LINKED ISSUE #21: Errors when watcher backend is given broken symlinks
I'm on Linux kernel 4.1.0, rsnotify 2.1.0 and Emacs 24.5.

My code is as simple as:

```rust
fn _watch (p: &Path) -> Result<(), Error>{
    let (tx, rx) = channel();
    let mut watcher: RecommendedWatcher = try!(Watcher::new(tx));
    println!("watcher init");
    try!(watcher.watch(p));
    println!("watching");
    let _ = rx.recv();
    Ok(())
}
```

Every time I modified files in Emacs, `watcher.watch(p)` returns error:

```
Io(Error { repr: Os { code: 2, message: "No such file or directory" } })
```

If I `ls -al` the watched directory, I'm getting:

```
 $ ls -al examples/templates  
drwxr-xr-x 2 nsun nsun 4096 Jul  6 21:04 .
drwxr-xr-x 3 nsun nsun 4096 Jul  4 10:37 ..
lrwxrwxrwx 1 nsun nsun   31 Jul  6 21:04 .#index.hbs -> nsun@thinkless.17462:1435199339
-rw-r--r-- 1 nsun nsun  279 Jul  6 20:57 index.hbs
```

The `.#index.hbs` symbol link, as [the SO question](http://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files) said, is Emacs lockfile. 

I'm not quite sure if this is an rsnotify issue, anything suggestion or workaround are welcomed.

### LINKED ISSUE #31: consider using walkdir crate
We might want to switch over to @BurntSushi's [walkdir](https://github.com/BurntSushi/walkdir) crate which may end up being more popular and therefore (hopefully) better maintained than the one @passcod extracted into walker.

We can evaluate this further after some time to see how things pan out, but the stuff from @BurntSushi is solid.

### PR DESCRIPTION
**Pull request by passcod**
Fixes #31
Fixes #21
Might help with #17

@SirVer, @sunng87, and @JIghtuse: Could you check with this branch for the behaviour you reported?

### CODE REVIEW

**Comment by JIghtuse** [comment]
@passcod works for me, thanks!

**Comment by sunng87** [comment]
@passcod Thanks! I will verify this later today.

**Comment by sunng87** [comment]
I confirmed #21 is fixed!

**Comment by sunng87** [comment]
@passcod Any update on this patch?

**Comment by sunng87** [comment]
@passcod Any update for this patch?

**Comment by passcod** [comment]
Busy weeks, xmas season etc... release incoming!

**Comment by sunng87** [comment]
Thanks @passcod !

**Comment by passcod** [comment]
Shipped in v2.5.2.

**Comment by sunng87** [comment]
Thanks!

**Pull request merged**
